// Auto-generated by scripts/parse-pravilnik.mjs from pravilnik-javni-prihodi.pdf
// (Porezna uprava FBiH, Pravilnik o načinu uplate javnih prihoda — prečišćeni tekst)
// Do not edit by hand — re-run the parser to regenerate.
// Source: https://www.pufbih.ba/v1/public/upload/zakoni/94b8a-pravilnik-o-nacinu-uplate-javnih-prihoda-preciscen-tekst.pdf

export type VrstaPrihoda = {
  code: string;
  name: string;
  section: string;
};

export type EkonomskaGrupa = {
  code: string;
  name: string;
  items: VrstaPrihoda[];
};

export type BudzetskaOrganizacija = {
  kod: string;
  naziv: string;
};

export const BUDZETSKE_ORGANIZACIJE: BudzetskaOrganizacija[] = [
  {
    "kod": "5102001",
    "naziv": "Federalni zavod za PIO/MIO"
  }
];

export const VRSTE_PRIHODA_GROUPS: EkonomskaGrupa[] = [
  {
    "code": "711",
    "name": "Porezi na dobit pojedinca i preduzeća",
    "items": [
      {
        "code": "711111",
        "name": "Porez na dobit od privredne i profesionalne djelatnosti",
        "section": "12. Zaostale uplate poreza"
      },
      {
        "code": "711112",
        "name": "Porez na dobit od poljoprivredne djelatnosti",
        "section": "12. Zaostale uplate poreza"
      },
      {
        "code": "711113",
        "name": "Porez po osnovu autorskih prava, patenata i tehničkih unapređenja",
        "section": "12. Zaostale uplate poreza"
      },
      {
        "code": "711114",
        "name": "Porez na ukupan prihod fizičkih lica",
        "section": "12. Zaostale uplate poreza"
      },
      {
        "code": "711115",
        "name": "Porez na prihod od imovine i imovinskih prava",
        "section": "12. Zaostale uplate poreza"
      },
      {
        "code": "711211",
        "name": "Porez na dobit",
        "section": "9. Porez na dobit preduzeća"
      },
      {
        "code": "711212",
        "name": "Porez po odbitku",
        "section": "9. Porez na dobit preduzeća"
      },
      {
        "code": "711911",
        "name": "Porez na dobit banaka",
        "section": "10. Porez na dobit banaka i drugih finansijskih organizacija, društava za osiguranje"
      },
      {
        "code": "711912",
        "name": "Porez na dobit mikrokreditnih organizacija",
        "section": "10. Porez na dobit banaka i drugih finansijskih organizacija, društava za osiguranje"
      },
      {
        "code": "711913",
        "name": "Porez na dobit društava za osiguranje imovine i lica",
        "section": "10. Porez na dobit banaka i drugih finansijskih organizacija, društava za osiguranje"
      },
      {
        "code": "711914",
        "name": "Porez na dobit društava za reosiguranje imovine i lica",
        "section": "10. Porez na dobit banaka i drugih finansijskih organizacija, društava za osiguranje"
      },
      {
        "code": "711915",
        "name": "Porez na dobit pravnih lica iz oblasti elektroprivrede",
        "section": "10. Porez na dobit banaka i drugih finansijskih organizacija, društava za osiguranje"
      },
      {
        "code": "711916",
        "name": "Porez na dobit pravnih lica iz oblasti pošte i telekomunikacija",
        "section": "10. Porez na dobit banaka i drugih finansijskih organizacija, društava za osiguranje"
      },
      {
        "code": "711917",
        "name": "Porez na dobit pravnih lica iz oblasti igara na sreću",
        "section": "10. Porez na dobit banaka i drugih finansijskih organizacija, društava za osiguranje"
      },
      {
        "code": "711918",
        "name": "Porez po odbitku",
        "section": "10. Porez na dobit banaka i drugih finansijskih organizacija, društava za osiguranje"
      },
      {
        "code": "711919",
        "name": "Ostali porezi na dobit pojedinca i preduzeća",
        "section": "10. Porez na dobit banaka i drugih finansijskih organizacija, društava za osiguranje"
      }
    ]
  },
  {
    "code": "712",
    "name": "Doprinosi za socijalna osiguranja",
    "items": [
      {
        "code": "712111",
        "name": "Doprinos za zdravstveno osiguranje",
        "section": "21. Doprinosi"
      },
      {
        "code": "712112",
        "name": "Doprinos za penzijsko i invalidsko osiguranje",
        "section": "21. Doprinosi"
      },
      {
        "code": "712113",
        "name": "Doprinos za osiguranje od nezaposlenosti",
        "section": "21. Doprinosi"
      },
      {
        "code": "712114",
        "name": "Dodatni doprinos za penzijsko- invalidsko osiguranje",
        "section": "21. Doprinosi"
      },
      {
        "code": "712115",
        "name": "Dodatni doprinos za zdravstveno osiguranje",
        "section": "21. Doprinosi"
      },
      {
        "code": "712116",
        "name": "Doprinos za zdravstveno osiguranje iz primitaka od druge samostalne djelatnosti i povremenog samostalnog rada",
        "section": "21. Doprinosi"
      },
      {
        "code": "712124",
        "name": "Sredstva za volontere radi osiguranja za slučaj povrede na radu ili profesionalne bolesti",
        "section": "21. Doprinosi"
      },
      {
        "code": "712125",
        "name": "Sredstva za pripravnike radi osiguranja za slučaj povrede na radu i profesionalne bolesti",
        "section": "21. Doprinosi"
      },
      {
        "code": "712126",
        "name": "Doprinos za penzijsko i invalidsko osiguranje na primitke od druge samostalne djelatnosti i povremenog samostalnog rada",
        "section": "21. Doprinosi"
      },
      {
        "code": "712131",
        "name": "Doprinos za penzijsko i invalidsko osiguranje koje za nezaposlene osobe plaćaju kantonalne službe za zapošljavanje",
        "section": "21. Doprinosi"
      },
      {
        "code": "712132",
        "name": "Doprinos za zdravstveno osiguranje poljoprivrednika",
        "section": "21. Doprinosi"
      },
      {
        "code": "712133",
        "name": "Doprinos za zdravstveno osiguranje koje za nezaposlene osobe plaćaju kantonalne službe za zapošljavanje",
        "section": "21. Doprinosi"
      },
      {
        "code": "712134",
        "name": "Doprinos za zdravstveno osiguranje licima kojima je priznat izbjeglički status",
        "section": "21. Doprinosi"
      },
      {
        "code": "712191",
        "name": "Doprinos za zdravstveno osiguranje radnika na radu u inostranstvu",
        "section": "21. Doprinosi"
      }
    ]
  },
  {
    "code": "713",
    "name": "Porezi na plaću i radnu snagu",
    "items": [
      {
        "code": "713111",
        "name": "Porez na plaću i druga lična primanja",
        "section": "12. Zaostale uplate poreza"
      },
      {
        "code": "713113",
        "name": "Porez na dodatna primanja",
        "section": "12. Zaostale uplate poreza"
      }
    ]
  },
  {
    "code": "714",
    "name": "Porezi na imovinu",
    "items": [
      {
        "code": "714111",
        "name": "Porez na imovinu od fizičkih lica",
        "section": "14. Porezi na imovinu"
      },
      {
        "code": "714112",
        "name": "Porez na imovinu od pravnih lica",
        "section": "14. Porezi na imovinu"
      },
      {
        "code": "714113",
        "name": "Porez na imovinu za motorna vozila",
        "section": "14. Porezi na imovinu"
      },
      {
        "code": "714121",
        "name": "Porez na nasljeđe i poklone",
        "section": "14. Porezi na imovinu"
      },
      {
        "code": "714131",
        "name": "Porez na promet nepokretnosti - fizičkih lica",
        "section": "14. Porezi na imovinu"
      },
      {
        "code": "714132",
        "name": "Porez na promet nepokretnosti pravnih lica",
        "section": "14. Porezi na imovinu"
      },
      {
        "code": "714191",
        "name": "Ostali porezi na imovinu",
        "section": "14. Porezi na imovinu"
      }
    ]
  },
  {
    "code": "715",
    "name": "Domaći porezi na dobra i usluge (zaostali)",
    "items": [
      {
        "code": "715131",
        "name": "Porez na promet proizvoda za koje se porez na promet proizvoda plaća po općoj stopi od 20% koja je propisana članom 11. Zakona o porezu na promet proizvoda i usluga, osim proizvoda, koji prema odre…",
        "section": "8. Zaostale obaveze po osnovu poreza na promet ostalih proizvoda i usluga"
      },
      {
        "code": "715132",
        "name": "Porez na promet proizvoda iz člana 12. Zakona o porezu na promet proizvoda i usluga za koje se porez na promet proizvoda plaća po nižoj stopi, osim proizvoda iz člana 12. stav 1. tač. 1., 2., 4., 1…",
        "section": "8. Zaostale obaveze po osnovu poreza na promet ostalih proizvoda i usluga"
      },
      {
        "code": "715136",
        "name": "Porez na promet proizvoda za koje obveznik ne posjeduje vjerodostojnu dokumentaciju",
        "section": "8. Zaostale obaveze po osnovu poreza na promet ostalih proizvoda i usluga"
      },
      {
        "code": "715137",
        "name": "Kaznena kamata",
        "section": "8. Zaostale obaveze po osnovu poreza na promet ostalih proizvoda i usluga"
      },
      {
        "code": "715141",
        "name": "Porez na promet usluga, osim usluga u građevinarstvu",
        "section": "8. Zaostale obaveze po osnovu poreza na promet ostalih proizvoda i usluga"
      },
      {
        "code": "715211",
        "name": "Porez na dobitke od igara na sreću",
        "section": "12. Zaostale uplate poreza"
      },
      {
        "code": "715912",
        "name": "Porez na promet naftnih derivata po nižoj stopi iz člana 12. stav 1. tač. 13. i 16. Zakona o porezu na promet proizvoda i usluga",
        "section": "8. Zaostale obaveze po osnovu poreza na promet ostalih proizvoda i usluga"
      },
      {
        "code": "715913",
        "name": "Porez na promet energenata po nižoj stopi iz člana 12. stav 1. tač",
        "section": "8. Zaostale obaveze po osnovu poreza na promet ostalih proizvoda i usluga"
      },
      {
        "code": "715914",
        "name": "Porez na promet osnovnih proizvoda poljoprivrede, ribarstva i proizvoda koji služe za ljudsku ishranu iz člana 12. stav 1. tač. 1. i",
        "section": "8. Zaostale obaveze po osnovu poreza na promet ostalih proizvoda i usluga"
      },
      {
        "code": "715915",
        "name": "Porez na promet osnovnih proizvoda za građevinarstvo iz člana 12. stav 1. tačka 12. Zakona o porezu na promet proizvoda i usluga i porez na promet usluga u građevinarstvu koji se obračunava na osno…",
        "section": "8. Zaostale obaveze po osnovu poreza na promet ostalih proizvoda i usluga"
      }
    ]
  },
  {
    "code": "716",
    "name": "Porez na dohodak",
    "items": [
      {
        "code": "716111",
        "name": "Prihodi od poreza na dohodak fizičkih lica od nesamostalne djelatnosti",
        "section": "11. Porez na dohodak"
      },
      {
        "code": "716112",
        "name": "Prihodi od poreza na dohodak fizičkih lica od samostalne djelatnosti",
        "section": "11. Porez na dohodak"
      },
      {
        "code": "716113",
        "name": "Prihodi od poreza na dohodak fizičkih lica od imovine i imovinskih prava",
        "section": "11. Porez na dohodak"
      },
      {
        "code": "716114",
        "name": "Prihodi od poreza na dohodak fizičkih lica od ulaganja kapitala",
        "section": "11. Porez na dohodak"
      },
      {
        "code": "716115",
        "name": "Prihodi od poreza na dohodak fizičkih lica na dobitke od nagradnih igara i igara na sreću",
        "section": "11. Porez na dohodak"
      },
      {
        "code": "716116",
        "name": "Prihodi od poreza na dohodak od drugih samostalnih djelatnosti iz Člana 12. stav (4) Zakona o porezu na dohodak",
        "section": "11. Porez na dohodak"
      },
      {
        "code": "716117",
        "name": "Prihodi od poreza na dohodak po konačnom obračunu",
        "section": "11. Porez na dohodak"
      }
    ]
  },
  {
    "code": "717",
    "name": "Prihodi od indirektnih poreza",
    "items": [
      {
        "code": "717111",
        "name": "Prihodi od indirektnih poreza koji pripadaju Federaciji",
        "section": "7. Prihodi od indirektnih poreza"
      },
      {
        "code": "717114",
        "name": "Prihodi od indirektnih poreza na ime finansiranja autocesta u Federaciji",
        "section": "7. Prihodi od indirektnih poreza"
      },
      {
        "code": "717121",
        "name": "Prihodi od indirektnih poreza koji pripadaju kantonima",
        "section": "7. Prihodi od indirektnih poreza"
      },
      {
        "code": "717131",
        "name": "Prihodi od indirektnih poreza koji pripadaju direkcijama cesta",
        "section": "7. Prihodi od indirektnih poreza"
      },
      {
        "code": "717141",
        "name": "Prihodi od indirektnih poreza koji pripadaju jedinicama lokalne samouprave",
        "section": "7. Prihodi od indirektnih poreza"
      },
      {
        "code": "717151",
        "name": "Prihodi od indirektnih poreza koji pripadaju Gradu Sarajevu",
        "section": "7. Prihodi od indirektnih poreza"
      }
    ]
  },
  {
    "code": "719",
    "name": "Ostali porezi",
    "items": [
      {
        "code": "719111",
        "name": "Ostali porezi",
        "section": "15. Ostali porezi"
      },
      {
        "code": "719114",
        "name": "Poseban porez na plaću za zaštitu od prirodnih i drugih nesreća",
        "section": "13. Obaveze po osnovu posebnog poreza za zaštitu od prirodnih i drugih nesreća"
      },
      {
        "code": "719115",
        "name": "Poseban porez za zaštitu od prirodnih i drugih nesreća po osnovu ugovora o djelu i privremenih i povremenih poslova",
        "section": "13. Obaveze po osnovu posebnog poreza za zaštitu od prirodnih i drugih nesreća"
      },
      {
        "code": "719116",
        "name": "Porez na potrošnju u ugostiteljstvu od pravnih lica",
        "section": "15. Ostali porezi"
      },
      {
        "code": "719117",
        "name": "Porez na potrošnju u ugostiteljstvu od fizičkih lica",
        "section": "15. Ostali porezi"
      }
    ]
  },
  {
    "code": "721",
    "name": "Prihodi od preduzetničkih aktivnosti i imovine",
    "items": [
      {
        "code": "721111",
        "name": "Prihodi od dividendi i udjela u profitu u državnim preduzećima i finansijskim institucijama",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721112",
        "name": "Prihodi od davanja prava na eksploataciju prirodnih resursa",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721113",
        "name": "Prihod od finansijske i nefinansijske imovine – od Civilne avijacije",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721114",
        "name": "Prihodi od davanja prava patenata i autorskih prava",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721119",
        "name": "Ostali prihodi od finansijske i nematerijalne imovine",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721121",
        "name": "Prihodi od iznajmljivanja zemljišta",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721122",
        "name": "Prihodi od iznajmljivanja poslovnih prostora i ostale materijalne imovine",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721123",
        "name": "Prihodi od iznajmljivanja vozila",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721124",
        "name": "Prihodi od iznajmljivanja opreme",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721129",
        "name": "Prihodi od iznajmljivanja ostale materijalne imovine",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721192",
        "name": "Povrat anuiteta od krajnjih korisnika za otplatu kredita",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721211",
        "name": "Prihodi od kamate za depozite u banci",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721214",
        "name": "Prihodi od GSM licence",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721215",
        "name": "Prihod po osnovu kamata na investirana javna sredstva",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721219",
        "name": "Ostali prihodi od finansijske i nematerijalne imovine",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721225",
        "name": "Prihodi od zakupa javnog vodnog dobra na površinskim vodama I kategorije",
        "section": "18. Posebne naknade"
      },
      {
        "code": "721226",
        "name": "Prihodi od zakupa javnog vodnog dobra na površinskim vodama II kategorije Prihodi od vodnih naknada, utvrđen i Zakonom o vodama (",
        "section": "18. Posebne naknade"
      },
      {
        "code": "721227",
        "name": "Prihodi od zakupa korištenja sportsko-privrednih lovišta 19.1.3.a",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721231",
        "name": "Prihodi ostvareni od prometa Lutrije BiH",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721232",
        "name": "Prihodi ostvareni prodajom stanova",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721233",
        "name": "Prihodi od prodaje stanova koji su u vlasništvu nadležnih nivoa vlasti",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721239",
        "name": "Ostali prihodi od imovine",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721311",
        "name": "Kamate primljene od pozajmica Državi",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721312",
        "name": "Kamate primljene od pozajmica Federaciji",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721313",
        "name": "Kamate primljene od pozajmica Republici Srpskoj",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721314",
        "name": "Kamate primljene od pozajmica kantonima",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721315",
        "name": "Kamate primljene od pozajmica gradovima",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721316",
        "name": "Kamate primljene od pozajmica općinama",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721317",
        "name": "Kamate primljene od pozajmica mjesnim zajednicama",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721321",
        "name": "Kamate primljene od pozajmica pojedincima",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721322",
        "name": "Kamate primljene od pozajmica neprofitnim organizacijama",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721331",
        "name": "Kamate primljene od pozajmica javnim preduzećima",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721511",
        "name": "Prihodi od pozitivnih kursnih razlika",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721611",
        "name": "Prihodi od privatizacije stanova",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721612",
        "name": "Prihodi od privatizacije banaka",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721613",
        "name": "Prihodi od privatizacije preduzeća",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721614",
        "name": "Prihodi od privatizacije poslovnih prostora",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721615",
        "name": "Prihodi od ostalih vidova privatizacije",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721711",
        "name": "Prihodi po osnovu obračunate premije za izdatu garanciju",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "721712",
        "name": "Prihodi po osnovu obračunate provizije za izdatu garanciju",
        "section": "19. Ostali neporezni prihodi"
      }
    ]
  },
  {
    "code": "722",
    "name": "Naknade, takse i prihodi od pružanja javnih usluga",
    "items": [
      {
        "code": "722111",
        "name": "Taksa za detašmane",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722112",
        "name": "Federalne administrativne takse",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722113",
        "name": "Putničke takse - naknade za unapređenje avio prometa u Federaciji BiH",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722114",
        "name": "Federalna taksa za korištenje autocesta (cestarina)",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722115",
        "name": "Posebna taksa za izmirenje duga za isporuku prirodnog gasa",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722116",
        "name": "Taksa za uspostavu rezervi naftnih derivata",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722121",
        "name": "Kantonalne administrativne takse",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722131",
        "name": "Općinske administrativne takse",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722132",
        "name": "Takse za držanje pasa",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722133",
        "name": "Takse za ovjeravanje dokumenata",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722134",
        "name": "Takse za vjenčanja i druge civilne registracije",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722135",
        "name": "Druge općinske administrativne takse",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722211",
        "name": "Federalne sudske takse od pravnih lica",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722212",
        "name": "Federalne sudske takse od fizičkih lica",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722221",
        "name": "Kantonalne sudske takse",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722231",
        "name": "Općinske sudske takse",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722311",
        "name": "Kantonalne komunalne takse",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722321",
        "name": "Općinske komunalne takse",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722322",
        "name": "Općinske komunalne naknade za istaknutu firmu",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722329",
        "name": "Ostale općinske komunalne naknade i takse",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722411",
        "name": "Federalne takse i naknade za pokriće troškova kontrole kvaliteta poljoprivrednih proizvoda u vanjskom prometu",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722412",
        "name": "Takse za pokrivanje troškova i utvrđivanje zdravstvene ispravnosti životnih namirnica i predmeta opće upotrebe koji se uvoze",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722414",
        "name": "Naknade troškova branilaca po službenoj dužnosti",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722415",
        "name": "Naknade ostalih troškova kaznenog postupka",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722416",
        "name": "Naknada za tehnički pregled vozila koja pripada budžetu Federacije",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722417",
        "name": "Naknada za korištenje cestovnog zemljišta i obavljanje pratećih djelatnosti uz autoceste i brze ceste u Federaciji BiH",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722418",
        "name": "Naknada od prisilnog izvršenja putem drugog lica o trošku subjekta nadzora – FUZIP",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722419",
        "name": "Federalna naknada za obavljene obavezne kontrole pošiljki mineralnih đubriva pri uvozu u Federaciju Bosne i Hercegovine",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722421",
        "name": "Kantonalne naknade",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722422",
        "name": "Naknada za korištenje poljoprivrednog zemljišta u nepoljoprivredne svrhe",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722424",
        "name": "Naknada za tehnički pregled vozila koja pripada kantonima",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722425",
        "name": "Prihodi po osnovu „Dječije nedjelje“",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722426",
        "name": "Naknada za troškove smještaja korisnika u ustanove socijalne zaštite",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722429",
        "name": "Ostale kantonalne naknade",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722431",
        "name": "Naknada za dodijeljeno zemljište",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722432",
        "name": "Naknada za osiguranje od požara",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722433",
        "name": "Naknada za uređenje građevinskog zemljišta",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722434",
        "name": "Naknada za korištenje građevinskog zemljišta",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722435",
        "name": "Naknada po osnovu prirodnih pogodnosti – Renta",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722436",
        "name": "Naknada po osnovu tehničkog pregleda građevina",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722437",
        "name": "Naknada za postupak legalizacije javnih površina i građevina",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722441",
        "name": "Općinske komunalne naknade u skladu sa kantonalnim propisima za posebne namjene",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722442",
        "name": "Naknada za izgradnju i održavanje javnih skloništa",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722443",
        "name": "Naknada za korištenje hidroakumulacionog objekta izgrađenog na potopljenom području",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722444",
        "name": "Naknada za prihode ostvarene radom termoelektrana",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722449",
        "name": "Ostale općinske naknade",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722451",
        "name": "Naknada za opće korisne funkcije šuma",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722452",
        "name": "Naknada za obavljanje stručnih poslova u privatnim šumama",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722453",
        "name": "Naknada za izdvajanje iz šumsko- privrednog područja",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722454",
        "name": "Naknada za korištenje državnih šuma",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722455",
        "name": "Naknada u postupku promjene namjene šumskog zemljišta (krčenje šuma)",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722456",
        "name": "Naknada po osnovu prava služnosti državnog šumskog zemljišta",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722457",
        "name": "Naknada po osnovu zakupa državnog šumskog zemljišta",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722458",
        "name": "Naknada za eksproprirano državno šumsko zemljište",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722459",
        "name": "Ostali prihodi za korištenje, zaštitu i unapređenje šuma",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722461",
        "name": "Naknada za zauzimanje javnih površina",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722462",
        "name": "Naknade i kazne za parkiranje",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722463",
        "name": "Naknade za zakup javnih površina od kafea, restorana, kioska i pijaca",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722464",
        "name": "Naknade za skladištenje građevinskih materijala, kampinga, pristaništa i javnih manifestacija",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722465",
        "name": "Naknade za reklame postavljene na javnim površinama",
        "section": "17. Općinske naknade i takse"
      },
      {
        "code": "722471",
        "name": "Naknada za opće korisne funkcije šuma utvrđen a kantonalnim propisima",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722472",
        "name": "Naknada za obavljanje stručnih poslova u privatnim šumama utvrđen a kantonalnim propisima",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722473",
        "name": "Naknada za izdvajanje iz šumsko- privrednog područja utvrđen a kantonalnim propisima",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722474",
        "name": "Naknada za korištenje državnih šuma utvrđen a kantonalnim propisima",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722475",
        "name": "Naknada u postupku promjene namjene šumskog zemljišta (krćenje šuma) utvrđen a kantonalnim propisima",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722476",
        "name": "Naknada po osnovu prava služnosti državnog šumskog zemljišta utvrđen a kantonalnim propisima",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722477",
        "name": "Naknada po osnovu zakupa državnog šumskog zemljišta utvrđen a kantonalnim propisima",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722479",
        "name": "Ostali prihodi za korištenje, zaštitu i unapređenje šuma utvrđen i kantonalnim propisima",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722481",
        "name": "Naknade za privređivanje igara na sreću koji pripadaju Budžetu Federacije Bosne i Hercegovine",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722511",
        "name": "Federalna naknada za uvjerenje o veterinarskozdravstvenom stanju životinja iz uvoza",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722512",
        "name": "Federalne naknade za obavezni zdravstveni pregled bilja u prometu preko teritorije Federacije",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722513",
        "name": "Federalne naknade za izvršeni veterinarsko-sanitarni pregled u prometu preko teritorije Federacije",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722514",
        "name": "Federalna naknada za izvršene veterinarsko –zdravstvene preglede i kontrolu u zemlji",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722515",
        "name": "Naknada za korištenje podataka izmjere katastra",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722516",
        "name": "Naknada za vršenje usluga iz oblasti premjera i katastra",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722517",
        "name": "Naknada za troškove postupka distribucije bilateralnih transportnih dozvola dodijeljenih domaćim prijevoznicima",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722518",
        "name": "Naknade po osnovu tehničkih pregleda građevina i po osnovu stručnih ispita",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722519",
        "name": "Naknada za sigurnost plovidbe koju plaćaju inostrana plovila i naknada za odobrenje za plovidbu inostranih plovila u teritorijalnim vodama Bosne i Hercegovine",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722521",
        "name": "Posebna vodna naknada za zaštitu voda za transportna sredstva koja za pogon koriste naftu ili naftne derivate",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722522",
        "name": "Posebna vodna naknada za zaštitu voda (ispuštanje otpadnih voda, uzgoj ribe, upotrebu vještačkih đubriva i hemikalija za zaštitu bilja)",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722523",
        "name": "Posebna vodna naknada za korištenje površinskih i podzemnih voda za javno vodosnabdijevanje",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722524",
        "name": "Posebna vodna naknada za korištenje površinskih i podzemnih voda, za flaširanje vode i mineralne vode, za uzgoj ribe u ribnjacima, za navodnjavanje i druge namjene",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722525",
        "name": "Posebna vodna naknada za korištenje površinskih i podzemnih voda za industrijske procese, uključuju ći i termoelektrane",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722526",
        "name": "Posebna vodna naknada za korištenje vode za proizvodnju električne energije u hidroelektranama",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722527",
        "name": "Posebna vodna naknada za važenje materijala iz vodotoka",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722528",
        "name": "Posebna vodna naknada za zaštitu od poplava",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722529",
        "name": "Opća vodna naknada",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722531",
        "name": "Naknada za upotrebu cesta za vozila pravnih lica",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722532",
        "name": "Naknada za upotrebu cesta za vozila građana",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722534",
        "name": "Naknada za vanrednu upotrebu inostranih motornih i priključnih vozila",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722535",
        "name": "Posebna naknada za službu",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722536",
        "name": "Naknada za vanrednu upotrebu motornih i priključnih vozila u zemlji",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722537",
        "name": "Naknade za ceste što se plaćaju za vanrednu upotrebu javnih cesta zbog opterećenja i učestalosti vozila (vanredni prijevoz)",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722538",
        "name": "Naknada za korištenje cestovnog zemljišta",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722539",
        "name": "Naknada za postavljanje reklamnih panoa",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722541",
        "name": "Naknada za korištenje opće korisnih funkcija šuma",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722542",
        "name": "Sredstva za proširenu biološku reprodukciju šuma",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722543",
        "name": "Naknada za krćenje šuma",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722544",
        "name": "Naknada za ograničenje korištenja šuma",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722545",
        "name": "Sredstva za jednostavnu biološku reprodukciju šuma",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722546",
        "name": "Sredstva na promet šuma",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722551",
        "name": "Naknada zagađivaća okoliša pravnih lica",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722552",
        "name": "Naknada zagađivaća okoliša fizičkih lica",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722553",
        "name": "Naknada korisnika okoliša pravnih lica",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722554",
        "name": "Naknada korisnika okoliša fizičkih lica",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722555",
        "name": "Posebne naknade za okoliš koje plaćaju pravna lica pri svakoj registraciji motornih vozila",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722556",
        "name": "Posebne naknade za okoliš koje plaćaju fizička lica pri svakoj registraciji motornih vozila",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722557",
        "name": "Posebne naknade za okoliš",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722558",
        "name": "Opće naknade za okoliš",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722561",
        "name": "Prihodi Crvenog križa/Crvenog krsta od naknada organiziranja manifestacija Crvenog križa/krsta",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722562",
        "name": "Naknada za korištenje objekata sigurnosti u unutrašnjim i teritorijalnim vodama Bosne i Hercegovine",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722563",
        "name": "Naknada domaćih i inostranih brodova za prijevoz putnika preko morskog akvatorija Neum-Klek",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722564",
        "name": "Naknade za privremeno obustavljanje održavanja polaska ili reda vožnje",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722565",
        "name": "Ostale naknade za ceste po posebnim propisima",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722566",
        "name": "Sredstva po osnovu nagradnih natječaja i nagradnih igara",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722567",
        "name": "Članarine obrtničkim komorama",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722568",
        "name": "Sredstva za podsticanje rehabilitacije i zapošljavanja lica sa invaliditetom koja plaćaju subjekti u državnim organima",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722569",
        "name": "Sredstva za podsticanje rehabilitacije i zapošljavanja lica sa invaliditetom koja plaćaju privredni i drugi subjekti",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722571",
        "name": "Naknada za pregled aerodroma radi dobijanja potvrde aerodromskog operatora",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722572",
        "name": "Naknada za utvrđivanje osposobljenosti avionskog i drugog stručnog osoblja, izdavanja odobrenja za rad organizacijama za obuku i zdravstvenim ustanovama, koje obavljaju ljekarske preglede avionskog…",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722573",
        "name": "Naknada za provođenje operacija avionima u komercijalne svrhe",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722574",
        "name": "Naknade za izvršeni pregled aviona",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722581",
        "name": "Posebna naknada za zaštitu od prirodnih i drugih nesreća gdje je osnovica zbirni iznos neto plaća",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722582",
        "name": "Posebna naknada za zaštitu od prirodnih i drugih nesreća gdje je osnovica zbirni iznos neto primitaka po osnovu druge samostalne djelatnosti i povremenog samostalnog rada",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722583",
        "name": "Naknada za vatrogasne jedinice iz premije osiguranja imovine od požara i prirodnih sila",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722584",
        "name": "Naknada iz funkcionalne premije osiguranja motornih vozila za vatrogasne jedinice",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722585",
        "name": "Naknada za zajedničke profesionalne vatrogasne jedinice iz premije osiguranja imovine od požara i prirodnih sila",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722586",
        "name": "Naknada za zajedničke profesionalne vatrogasne jedinice iz funkcionalne premije osiguranja motornih vozila Posebne naknade za zaštitu od prirodnih i drugih nesreća uplaćuju se na račun javnih priho…",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722591",
        "name": "Naknada za polaganje stručnih ispita",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722592",
        "name": "Članarine turističkih zajednica",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722593",
        "name": "Boravišna taksa",
        "section": "18. Posebne naknade"
      },
      {
        "code": "722594",
        "name": "Naknade za obrasce koje izdaju kapetanije",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722595",
        "name": "Naknade za baždarenje čamaca",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722596",
        "name": "Naknade za pregled čamaca",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722597",
        "name": "Federalna naknada od izdatih licenci, uvjerenja, certifikata i stručnih publikacija",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722599",
        "name": "Mjesečna naknada za priređivanje igara na sreću klađenja (kladionice, automati, kasina, internet igre) i naknada za postavljanje uređaja za priređivanje klađenja",
        "section": "16. Naknade i takse"
      },
      {
        "code": "722611",
        "name": "Prihodi od pružanja usluga građanima",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722612",
        "name": "Prihodi od pružanja usluga pravnim licama",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722613",
        "name": "Prihodi od pružanja usluga drugima",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722614",
        "name": "Prihodi od naučno-istraživačkog rada",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722621",
        "name": "Prihodi od pružanja usluga drugim nivoima vlasti",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722622",
        "name": "Prihodi od pružanja usluga drugim nivoima vlasti – za pritvorena lica",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722623",
        "name": "Prihodi od pružanja usluga drugim nivoima vlasti – refundacija za štampanje matičnih knjiga i ostalih obrazaca",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722631",
        "name": "Vlastiti prihodi budžetskih korisnika",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722632",
        "name": "Prihodi od mjenica",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722633",
        "name": "Prihodi od prodaje taksenih maraka",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722634",
        "name": "Prihodi od prodaje mjeničnih blanketa",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722711",
        "name": "Povrat invalidnina iz ranijih godina",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722712",
        "name": "Povrat pogrešno isplaćenih plaća",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722713",
        "name": "Povrat duplo plaćenih obaveza",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722714",
        "name": "Povrat premija u primarnoj poljoprivrednoj proizvodnji",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722715",
        "name": "Povrati naknada troškova zaposlenih",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722719",
        "name": "Ostali povrati",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722721",
        "name": "Uplate za prekoraćenje troškova PTT usluga",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722731",
        "name": "Uplata anuiteta za date kredite pojedincima",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722732",
        "name": "Prihod od troškova naplate po osnovu pokretanja postupka prinudne naplate",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722733",
        "name": "Prihod od troškova zapljene u postupku prinudne naplate",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722741",
        "name": "Naplata premije osiguranja",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722751",
        "name": "Primljene namjenske donacije neplanirane u budžetu",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722761",
        "name": "Uplaćene refundacije bolovanja iz ranijih godina",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722791",
        "name": "Ostale neplanirane uplate",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "722792",
        "name": "Prihodi od prekršenog garantnog otpusta (prihodi od garancija)",
        "section": "19. Ostali neporezni prihodi"
      }
    ]
  },
  {
    "code": "723",
    "name": "Novčane kazne (neporezne)",
    "items": [
      {
        "code": "723111",
        "name": "Novčane kazne za prekršaje koje pripadaju Federaciji i troškovi prekršajnog postupka od fizičkih lica",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723112",
        "name": "Novčane kazne za prekršaje koje pripadaju Federaciji i troškovi prekršajnog postupka od pravnih lica",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723113",
        "name": "Novčane kazne za kaznena djela koje pripadaju Federaciji",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723114",
        "name": "Novčane kazne za prekršaje koje izriču federalni organi uprave i troškovi postupka",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723115",
        "name": "Novčane kazne za privredne prestupe koje pripadaju Federaciji i troškovi postupka",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723116",
        "name": "Novčane kazne za saobraćajne prekršaje",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723117",
        "name": "Novčane kazne za prekršaje koji su registrovani u registru novVanih kazni i troškovi prekršajnog postupka",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723118",
        "name": "Prihodi od prodaje oduzete robe po postupku Porezne uprave",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723119",
        "name": "Prihodi od prodaje oduzete robe po pravosnažnim rješenjima",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723121",
        "name": "Novčane kazne po kantonalnim propisima",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723122",
        "name": "Ostale kazne",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723123",
        "name": "Novčane kazne za prekršaje koje su registrovane u registru novčanih kazni i troškovi prekršajnog postupka",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723129",
        "name": "Ostali prihodi",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723131",
        "name": "Novčane kazne po općinskim propisima",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723132",
        "name": "Ostale kazne",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723133",
        "name": "Novčane kazne za prekršaje koje su registrovane u registru novčanih kazni i troškovi prekršajnog postupka",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723139",
        "name": "Ostali prihodi",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723141",
        "name": "Novčane kazne koje su propisane u Članu 16. Zakona o sukobu interesa u organima vlasti u Federaciji Bosne i Hercegovine",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "723142",
        "name": "Prihodi od imovinske koristi pribavljeni krivičnim djelom, oduzeti u skladu sa Članom 115. KriviVnog zakona Federacije Bosne i Hercegovine",
        "section": "19. Ostali neporezni prihodi"
      }
    ]
  },
  {
    "code": "731",
    "name": "Tekuće transfere",
    "items": [
      {
        "code": "731111",
        "name": "Primljeni tekući transferi od inostranih vlada",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "731121",
        "name": "Primljeni tekući transferi od međunarodnih organizacija",
        "section": "19. Ostali neporezni prihodi"
      }
    ]
  },
  {
    "code": "732",
    "name": "Kapitalne primljene transfere",
    "items": [
      {
        "code": "732111",
        "name": "Primljeni tekući transferi od Države",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732112",
        "name": "Primljeni tekući transferi od Federacije",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732113",
        "name": "Primljeni tekući transferi od Republike Srpske",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732114",
        "name": "Primljeni tekući transferi od kantona",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732115",
        "name": "Primljeni tekući transferi od gradova",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732116",
        "name": "Primljeni tekući transferi od općina",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732131",
        "name": "Transfer od Federalnog Zavoda za zapošljavanje",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732132",
        "name": "Transfer od Federalnog Zavoda zdravstvenog osiguranja i reosiguranja",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732141",
        "name": "Primljeni tekući transferi od FBiH – Uredba",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732142",
        "name": "Primljeni tekući transferi od FBiH – Uredba",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732143",
        "name": "Primljeni tekući transferi od FBiH za demobilizirane branioce i Članove njihove porodice",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732144",
        "name": "Primljeni tekući transferi od FBiH za branitelje po Zakonu o pravima branilaca i Članova njihovih porodica",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732145",
        "name": "Primljeni tekući transferi od FBiH za pokriće dijela penzija po osnovu Člana 94. Zakona o penzijskom i invalidskom osiguranju",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732146",
        "name": "Primljeni tekući transferi od FBiH za penzije bivše JNA u skladu sa Članom 139. Zakona o penzijskom i invalidskom osiguranju",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732147",
        "name": "Primljeni tekući transferi od FBiH – Uredba 1",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732148",
        "name": "Primljeni tekući transferi od FBiH – Zakon o službi u vojsci FBiH",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "732149",
        "name": "Primljeni tekući transferi od FBiH –",
        "section": "19. Ostali neporezni prihodi"
      }
    ]
  },
  {
    "code": "733",
    "name": "Grupa 733",
    "items": [
      {
        "code": "733111",
        "name": "Donacije od fizičkih lica",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "733112",
        "name": "Donacije od pravnih lica",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "733115",
        "name": "Donacije od fizičkih i pravnih lica za poticaj za zapošljavanje",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "733116",
        "name": "Donacije od domaćih fizičkih i pravnih lica za otklanjanje posljedica prirodne nesreće i obnovu područja zahvaćenih prirodnom nesrećom",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "733121",
        "name": "Donacije od inostranih fizičkih lica",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "733122",
        "name": "Donacije od inostranih pravnih lica",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "733125",
        "name": "Donacije od inostranih fizičkih i pravnih lica za poticaj za zapošljavanje",
        "section": "19. Ostali neporezni prihodi"
      },
      {
        "code": "733126",
        "name": "Donacije od inostranih fizičkih i pravnih lica za otklanjanje posljedica prirodne nesreće i obnovu područja zahvaćenih prirodnom nesrećom",
        "section": "19. Ostali neporezni prihodi"
      }
    ]
  }
];

export const VRSTE_PRIHODA_BY_CODE: Record<string, VrstaPrihoda> = Object.fromEntries(
  VRSTE_PRIHODA_GROUPS.flatMap((g) => g.items.map((it) => [it.code, it]))
);
